export enum JobApplicationState {
    APPLIED = "APPLIED",
    IN_PROGRESS = "IN_PROGRESS",
    REJECTED = "REJECTED",
    ACCEPTED = "ACCEPTED",
    ACCEPTED_FOR_INTERVIEW = "ACCEPTED_FOR_INTERVIEW"
}